### ISSUE TITLE
getSpawned is bogus when operating on objects

### ISSUE THREAD

**Issue by jtobin** [urbit/azimuth-js#15]
If passed an object (i.e. a cached point gotten via `getPoint`), `getSpawned` tries to return the value of an expected `spawned` property, which, alas, does not exist.

**Comment by Fang-** [comment]
Ah yes, that property was removed during the final round of contract changes. I missed its use here. `getSpawned` should now always call out to chain.

(There's an argument to be made for adding it to the object if the object doesn't have it, but I don't think we use that pattern anywhere yet, so let's not.)
