### ISSUE TITLE
Change children to kids?

### ISSUE THREAD

**Issue by cxk280** [urbit/azimuth-js#67]
One thing that recently came up on the bounty I'm working on under @jalehman is that Arvo refers to `kids`, but this repo refers to `children`. Is that something we want to change?

**Comment by Fang-** [comment]
Considering that [Azimuth.sol](https://github.com/urbit/azimuth/blob/master/contracts/Azimuth.sol) and [Ecliptic.sol](https://github.com/urbit/azimuth/blob/master/contracts/Ecliptic.sol) say "children" in some comments, but never "kids", probably not. Arvo is _downstream_ from Azimuth, anyway, so influences generally shouldn't flow the other way around.
