### ISSUE TITLE
Enable Travis.

### ISSUE THREAD

**Issue by jtobin** [urbit/azimuth-js#8]
The CI should just work™ now, but it needs to be enabled, and I don't have the rights to do so.  

**/petitions the king**

**Comment by jtobin** [comment]
(The CI will work but the tests will fail, presumably due to #9.)

**Comment by Fang-** [comment]
Who even is the king? I have no settings rights on this repo. Maybe @vvisigoth?

**Comment by vvisigoth** [comment]
you know who's king.

**Comment by vvisigoth** [comment]
I've enabled Travis for this repo and granted both of you admin rights.

**Comment by jtobin** [comment]
**/bows repeatedly while slinking out of issue in reverse**
