### ISSUE TITLE
Is there some way to use these bindings for L2 transactions?

### ISSUE THREAD

**Issue by cxk280** [urbit/azimuth-js#86]
If not, is there a plan to add that functionality?

**Comment by tomholford** [comment]
This is the package Bridge uses to interact with the L2 roller:

https://www.npmjs.com/package/@urbit/roller-api

**Comment by cxk280** [comment]
I have a considerable codebase optimized to use `azimuth-js`, so if such capability does not exist I'll propose it as a bounty. @tomholford thank you for pointing me toward the package Bridge uses though, as I'll definitely need that as a reference during any such project!

**Comment by cxk280** [comment]
That looks like it will work for me. Thanks for the pointer, @tomholford!
